require('dotenv').config()

const Discord = require('discord.js')
const client = new Discord.Client()
var messages = [
"Mmm",
"I don't want to be his queen. I want to go home.",
"I don't know.",
"Thank you ser...",
"Are you... from my country?",
"Thank you, Magister.",
"Ser Jorah I... I don't know how to say 'Thank you' in Dothraki.",
"Do you know the Common Tongue?",
"Is 'No' the only word that you know?",
"Have you ever seen a dragon?",
"Everywhere? Even in the East?",
"The Moon?",
"Leave me with her.",
"Why did the trader from Qarth tell you these stories?",
"How old were you?",
"Nine?!",
"Can you teach me how to make the Khal happy?",
"Will it take 3 years?",
"Well she... sounds like an interesting woman!",
"I... I don't think Drogo will like it with me on top..",
"*shakes head*",
"I... I don't think that this is the Dothraki way..",
"No!",
"Ajjalan anha zalat vitiherat yer hatif", 
"Do the Dothraki buy their slaves?",
"From who?",
"Tell them all to stop.",
"Until I command them otherwise.",
"Not a Queen... A Khaleesi.",
"No!",
"Please! Please, don't hurt him! Tell him: I don't want my brother harmed!",
"At.. jaka",
"Ath jahakar..",
"Athjahakar",
"Ooh... W-what are you doing?",
"Me rakh", 
"Anha sekke nesa.", 
"Hush now, it's alright. Irri, take her and leave us.",
"Why did you hit her?",
"I wasn't commanding you! I just wanted to invite you to supper!",
"It's a gift. I had it made for you",
"Please..",
"Stop.",
"You've no right to a braid, you've won no victories yet.",
"I am a Khaleesi of the Dothraki! I am the wife of the great Khal and I carry his son inside me! The next time you raise a hand to me, will be the last time you have hands.",
"Khalakka dothrae mr'anha",
"Ma me nem ahakee ma Rhaego!", 
"Viserys, please!",
"He says yes. You shall have a golden crown, that men shall tremble to behold.",
"No.",
"He was no dragon. Fire cannot kill a dragon.",
"K'asi assikhqoyisiri vezh adothrae nakhaan rhaesheseri", 
"Sorfosor nakho vosecchi. Sani sorfi vekha yomme. Sorfo athyolari anni.", 
"Rhaeshi, sek.", 
"Dalen rhaggat eveth ma ale: ido fini ovethi yomme.", 
"Me vos ador. Me...me...throne.", 
"Ador finaan khal nevasoe...che khaleesi.", 
"Can't you help me make him understand?",
"My brother.. was a fool, I know, but he was the rightful heir to the Seven Kingdoms.",
"Have I said something funny, Ser?",
"And because he had dragons.",
"You don't believe it!",
"Well, I'll come with you.",
"Rise.",
"I'd still like to taste that wine.",
"You honor me, ser!",
"I hope to repay your kindness someday",
"Something wrong?",
"Do as he says.",
"You will drink.",
"Ti mae k'asi, che Khal Drogo anesa valzerikh.", 
"Mago asta k'athjilari, zhey shekh ma shieraki anni. Anha ray qoraso san ohari asshekh majin mori nem vos osaji.", 
"Anha nem allayafak vassandik mora. Hash dothraki shafki'th saji mora hash mori jif kemoe ma moroa.", 
"Zhavvorsa vadakhera ma hrazef ma vaf akkate. ", 
"Anha Khaleesi. Anha assok yera sekosshi.", 
"Shekh ma shieraki anni zisa.", 
"Finne koalaki?",
"Who are you?",
"Me anni. Me vastoe.", 
"Azhas maan affisat zis yeri, shekh ma shieraki anni. Me azzisa anna jin tihat meyer qiyae.",
"Save him, and I will free you I swear it.",
"You must know a way! Some... some magic..",
"Do it. Save him.",
"Gold! Whatever you want!",
"My death.",
"*nods*",
"Kill her, and you kill your Khal!",
"I am your Khaleesi! I tell you what is forbidden!",
"Take her and leave. Take her!",
"No one will enter.",
"Bring him back to me.",
"I have to save him...",
"Jini vee",
"Vos! Yer laz vos", 
"The baby... is coming!",
"*moans*",
"Where is Khal Drogo?",
"Show me what I have bought with my son's life.",
"This is not life! When will he be as he was?",
"Leave us.",
"I have nothing more to fear from this woman. Go!",
"You knew what I was buying, and you knew the price.",
"This is not God's work! My child was innocent!",
"I spoke for you! I *saved* you!",
"Your life.",
"Shekh ma shieraki anni!", 
"Hash yer vineseri dothrakh ataki kishi, zhey shekh ma shieraki anni?", 
"Hash yer laz chari anna; hash yer ray vos o, attihas anna.", 
"Yer lajak. Yer ayyeyoon lajakoon. Anha zigerek yeroon lajat ajjin.", 
"Affin shekh yola she jimma ma drivoe she titha...Arrek yer ajadi save, shekh ma shieraki anni.", 
"They were not given to me to sell.",
"I must. You don't understand.",
"Is that what you fear?",
"You will be my Khalasar!",
"I see the faces of slaves! I free you!",
"Take off your collars, go if you wish, no one will stop you. But if you stay, it will be as brothers and sisters. As husbands and wives.",
"Ser Jorah, bind this woman to the pyre.",
"You swore to obey me.",
"I am Danaerys Stormborn, of House Targaryen, of the blood of Old Valyria. I *am* the Dragon's Daughter! And I swear to you, that those who would harm you would die screaming!",
"I will. But it's not your screams I want. Only your life.",
"He said they ate meat.",
"My brother didn't know anything about dragons. He didn't know anything about anything.",
"E",
"She was Drogo's first gift to me.",
"I promised to protect them. I promised them their enemies would die screaming. How do I make starvation scream?",
"Does it ever end?",
"And you're sure there's no other way.",
"No one will take my dragons.",
"As you are mine.",
"Zhey qoy qoyi!", 
"Zhey Rakharo, zhey Aggo, zhey Kovarro. Fichi hrazef zinayi kishi.", 
"Ma yer adothrae tith; ma yer heshtith; ma yer valshtith.", 
"Vaes, che thiri che drivi. Ma verakasaris ma voji. Che ashefaes che tozaraes che Havazzhife Zhokwa. Ezo athchilar Athasaroon Virzetha hatif kishi, ma reki vekha yomme moon.", 
"Rakharo. Yer athzalar nakhoki anni, zhey qoy qoyi.",
"Blood of my blood...",
"Who did this?",
"They will like it far less when I am done with them.",
"Affa, affa. Mori laz vos atthi oakah vosecchi.", 
"Affa. Kisha amariki vorsqoy ha maan. Majin anha astak yeraan asqoy, me-Rakharo adothrae kimi mae ajjalan.", 
"Jin vos sajo yeri.", 
"Zhey Qarth?", 
"Hash mori vazhi kishaan emralat?", 
"What do you know of this place?",
"I thought we were welcome here.",
"Horde?",
"My name is Danaerys-",
"You know me, my Lord?",
"And what should I call you?",
"The beauty of Quarth is legenda-",
"Qarth.",
"My... friend. We have travelled very far. We have no food, no water. Once I see my people fed I would be honored-",
"I am not a liar.",
"Where I come from, guests are treated with respect, not insulted at the gates.",
"What are you doing? You promised to receive me!",
"If you do not let us in, all of us *will* die!",
"Thirteen!",
"When my dragons are grown, we will take back what was stolen from me, and *destroy* those who have wronged me! We will lay waste to armies and burn cities to the ground! Turn us away, and we will burn you first.",
"It sounds wonderful.",
"Please excuse me for a moment",
"What are they doing?",
"Kisha nevaki mae! Yer laz vos vefenari mae, vos tavi mae, vos ivvisi mae.", 
"Kash athezar kishi vos akka.", 
"Hash idrik kishi vijazero kisha Athasaroon Virzetha hash yer zali zifichelat moon? Anha acharak vos alikh.", 
"My brother used to say the only thing the Dothraki know how to do is steal the things better men have built.",
"That's not the kind of Queen I'm going to be.",
"What is the House of the Undying?",
"*laughs*",
"The Seven Kingdoms are at war with one another! Four false kings destroying the country-",
"The Usurper is dead! The Starks fight the Lannisters! The Baratheons fight each other!",
"The time to strike is now! We need to find ships and an army, or we'll spend the rest of our lives rotting away at the edge of the world.",
"And if I'd listened to that advice outside the gates of Qarth, we'd all be dead by now.",
"Do not speak to me like I'm a child!",
"What do you want? Tell me.",
"Why?",
"So what would you have me do, as my advisor?",
"And how do I get this ship?",
"I look forward to meeting him.",
"The Spice King refuses me because I'm a bad investment, the Silk King won't supprt me because of his business with the Lannisters- why offend his best customer? And the Copper King offers me a single ship on the condition that I lie with him for a night. Does he think I will whore myself for a boat?",
"Where are they?",
"WHERE ARE MY DRAGONS?!",
"You came back.",
"Irri is dead.",
"She's dead. She died alone, she died for me, and I couldn't protect her.",
"We can't find her. She must be dead too.",
"I lead my people out of the Red Waste and into the slaughterhouse.",
"You went to find me a ship.",
"These people?",
"And who is to be trusted? Who are my people? The Targaryens? I only knew one, my brother, and he would've let a thousand men rape me if it would've gotten him a crown. The Dothraki? Most of them turned from me the day Khal Drogo fell from his horse.",
"The people in Westeros don't know I'm alive.",
"And then what? They'll pray for my return? They'll wave dragon banners and shout for my name? That's what my brother believed and he was a fool.",
"There it is, 'trust me'. And it's you I should trust, Ser Jorah? Only you?",
"I don't *need* trust any longer. I don't want it and I don't have room for it.",
"And you are too familiar.",
"Find my dragons.",
"Astapor?",
"They have my dragons. A mother does not flee without her children.",
"You should sail to Astapor, I'm sure you'll be safe there.",
"Then serve me. If my dragons are in the House of the Undying, then take me there.",
"And what of my magic? You saw me step into the fire, you watched the witch burn! What did the flames do to me? Do you remember?",
"They are my children. And they are the only children I will ever have. Take me to them.",
"Azhi morea kis tat.", 
"Jini athmovezar qoyi ven athmovezar fini fich yera anhoon—fini fich yera anhoon hatif…", 
"Ishish anha drivak vosma anha ray nesok mae vos. Ishish anha ma yeroon she Rhaeshi Ajjalani.", 
"Jini vena tikh meyer jif ti.",
"This is not my home. My home is across the sea where my people are waiting for me.",
"Dracarys.",
"Not fast enough. I can't wait that long.",
"I need an army.",
"The greatest *slave* soldiers in the world. The distinction means a great deal to some people.",
"It's too beautiful a day to argue.",
"Don't mock them. They're the first Dothraki who've ever been on a ship. They followed me across the poison water. If they'll do it, others will. And with a proper Khalasar-",
"They may suit my needs. Tell me of their training.",
"Tell the Good Master, there is no need-",
"You take a babe, from it's mothers eyes, kill it as she watches, and pay for her pain with a silver coin?",
"How many do you have to sell?",
"8000 *thousand* dead babies.",
"Once I own an army of slaves, what will I be?",
"*giggles*",
"The Warlocks.",
"I owe you my life, Ser.",
"You know this man?",
"For who?",
"Give me your water.",
"Drink.",
"The blood of my enemies, not the blood of innocents.",
"Do you disagree, Ser Barristan?",
"Did you know him well, Ser Barristan?",
"I wish I had known him. But he was *not* the last dragon.",
"They did not. I want to buy them all.",
"Yes. Eight thousand. And the ones still in training as well.",
"I will have them all, or take none. Many will fall in battle, I will need the boys to pick up the swords they drop.",
"I have dragons. I'll give you one.",
"One.",
"Done.",
"I'll take you as well. Now. You'll be Master Kraznys' gift to me; token of a bargain well struck.",
"You're both here to advise me. I value your advice. But if you ever question me in front of strangers again, you'll be advising someone else. Is that understood?",
"Do you have a name?",
"Do you have a family? Mother and a father you'd return to if you had a choice?",
"You belong to me now. It is your duty to tell the truth.",
"I offered water to one of the slaves dying on the Walk of Punishment. Do you know what he said to me? 'Let me die'.",
"Is it true what Master Kraznys told me about the Unsullied? About their obedience?",
"And what about you? You know that I'm taking you to war. You may go hungry, you may fall sick, you may be killed...",
"Yes. All men *must* die. But we are not men.",
"Is it done, then? They belong to me?",
"Dovaogēdys! Naejot memēbātās! Kelītīs!", 
"Zaldrīzes buzdari iskos daor.", 
"Nyke Daenerys Jelmāzmo hen Targārio Lentrot, hen Valyrio Uēpo ānogār iksan. Valyrio muño ēngos ñuhys issa.",
"Dovaogēdys! Āeksia ossēnātās, menti ossēnātās, qilōni pilos lue vale tolvie ossēnātās, yn riñe dōre ōdrikātās. Urnet luo buzdaro tolvio belma pryjātās!", 
"Dovaogēdys! Jevo glaesoti rȳ buzdari istiat. Kesy tubi jemot dāervi tepan.", 
"Henujagon jaelza lua vala mirre henujagon kostas, se daorys ziry ōdrikilza. Jemot kivio ñuhe tepan.",
"Yne sytivīlībilāt? Hae dāero valoti?", 
"These are the ones?",
"Keso glaesot iderēptot daor.", 
"Yn dāeri vali sīr issi. Se dāeri vali pōntalo syt gaomoti iderēbzi.",
"Jenti jevi jemēle iderēbilātās, qogrondo jevo hēdrȳ.", 
"Geltī aōhe nādīnās.",
"Skoroso jemēle brōzā?", 
"Torgo Nudho?", 
"Hēzīr, brōza jevi jemēle iderēbilātās. Mentyri idañe jevi ivestrilātās keskydoso gaomagon.", 
"Gadbag aōhe qrīdrughās. Muñar aōt teptas lue brōzi, iā mirre tolie iderēbās. Avy hoskas lue brōzi.", 
"I don't want half my army killed before I've crossed the Narrow Sea.",
"How many slaves are there in Yunkai?",
"Then we have two hundred thousand reasons to take the city.",
"Va oktio remȳti vale jikās.", 
"Belmurtī ivestrās kesīr pōnte jiōrinna se pōjon obūljarion mazōrīnna. Lodaor hēnkos vējose hae Astaprot Yunkai botilza.", 
"You may approach. Sit.",
"Good. My Unsullied need practice. I was told to blood them early.",
"My ship?",
"And what do you ask in return?",
"I have a gift for you as well. Your life.",
"And the lives of your Wise Masters, but I also want something in return. You will release every slave in Yunkai. Every man, woman, and child shall be given as much food, clothing, and property as they can carry as payment for their years of servitude. Reject this gift, and I shall show you no mercy.",
"I did. But my dragons made no promises, and you threatened their mother.",
"My gold. You gave it to me, remember? And I'll put it to good use. You'd be wise to do the same with my gift to you. Now get out.",
"What happens to things that don't bend? He said he had powerful friends. Who's he talking about?",
"Find out",
"You know these men?",
"Is he more titan or bastard?",
"How many?",
"Enough to make a difference?",
"It's hard to collect wages from a corpse. I'm sure the sellswords would prefer to fight for the winning side?",
"Let's talk to the Titan's Bastard about winning.",
"He will. A man who fights for gold can't afford to lose to a girl.",
"Give me your Second Songs and I may not have you gelded",
"Ser Barristan, how many men fight for the Second Sons?",
"We have more, don't we?",
"I'm only a young girl new to the ways of war, but perhaps a seasoned Captain like yourself can explain to me how you propose to defeat us.",
"You're very young to be a Captain.",
"Even if your numbers are right, you must admit the odds don't favor your side.",
"Or you could fight for me.",
"I would pay you as much, and more.",
"Ride with me and you'll never need another contract. You'll have gold and castles of your choosing when I take back the Seven Kingdoms.",
"A fortnight ago, I had no army. A year ago I had no dragons. You have two days to decide.",
"Bisi vali īlvyz zentyssy issi.", 
"You seem to be enjoying my wine. Perhaps you'd like a flagon to help you ponder.",
"A barrel, then.",
"Ser Barristan, if this comes to battle, kill that one first.",
"Nineteen?!",
"How can anyone speak nineteen languages?",
"Yes, well, it was either learn Dothraki or grunt at my husband... What do you mean *reasonably* well?",
"Zhey Drogo ast me-Dothraki thasho h’anhaan ven anha ray yol mehas. Me azh maan atjakhar.", 
"Well, I suppose I'm a bit out of practice...",
"What do you want?",
"Let her go.",
"You were sent here to kill me. So why haven't you?",
"What do your captains have to say about that?",
"Why?",
"Over what?",
"You're a strange man.",
"Oh then this is supposed to impress me?",
"Why would I trust a man who murders his comrades?",
"Will you fight for me?",
"Swear to me.",
"Where?",
"Jentys Dovaogēdyro syt iksā. Skoros otāpā?",
"You leave tonight.",
"We've been waiting a long time. Haven't we?",
"I don't know, you tell me. How long does it take to sack a city?",
"And Daario Naharis?", 
"How are the lessons coming?",
"You'll have to continue later. It's time.",
"What are they saying?", 
"Dāervose jevosy yne enkot daor. Jemot ziry tepagon koston daor. Dāerves jevys tepagon yne sytilībos daor. Jemēle mērī sytilības. Lo ziry arlī jaelāt, jemēlo syt ziry mazemagon jemo bēvilza. Tolvies jemys.", /
"Ser Barristan.",
"Where's Daario Naharis? Where's Grey Worm?",
"Gambling?",
"How long have they been at it?",
"What's the prize to winning this stupid contest?",
"That honor goes to Ser Jorah and Ser Barristan, as neither of them kept me waiting this morning. You two will ride in the rear guard and protect the livestock. And the last man holding his sword can find a new Queen to fight for.",
"Have you ever been to Meereen?",
"And?",
"And now an army of *former* slaves is marching to her gates. You think the Great Masters are worried?",
"You were told to ride at the *back* of the train.",
"Alright, what is this matter of strategy?",
"Would you like to walk at the back of the train instead of riding?",
"Would you like to walk without shoes?",
"You are a gambler, aren't you?",
"How many miles are there between here and Meereen?",
"You will do no such thing. I will see each and every one of their faces. Remove her collar before you bury her.",
"Are they attacking?",
"What is he doing?",
"I have something to say to the people of Meereen. First I will need this one to be quiet. Do I have a champion?",
"You are Captain of the Unsullied. I cannot risk you" 
"Which is why you must remain by my side.",
"You're my most trusted advisor, my most valued general, and my dearest friend. I will not gamble with your life.",
"Very well. You have quite an audience. Make it worth their while.",
"Yes. Win or lose. As long as the whole city's watching.",
"You sure you don't want a horse?",
"Horses are faster than men.",
"Daenerys Jelmāzmo iksan. Kostilus jevi āeksia yno bē pirtra jemot vestretis, iā daoruni jemot vestretis. Daoriot jemas. Doriar udra pōnto syt eman. Mērī jemī ivestran. ", 
"Ēlī Astaprot istan. Astaprot dohaertrossa sīr yno inkot iōrzi, dāeri. Hembar Yunkaihot istan. Yunkaihī dohaertrossa sīr yno inkot iōrzi, dāeri. Sesīr Mirinot mastan. ", 
"Jevys qrinuntys ikson daor. Jevys qrinuntys jemo paktot issa. Jevys qrinuntys jevor riñar laodissis ossēnīs. Jevys qrinuntys jemo syt mērī belma se boteri se udrāzmī ēzi. Udrāzmī jemot maghon daor. Iderennon maghan. Se jevo qrinuntoti pōjor gūrotriri maghan. Naejot! ", 
"Nābēmātās! ", 
"Remind me, Ser Jorah. How many children did the Great Masters nail to mileposts?",
"Yes, that was it.",
"I will answer injustice with justice.",
"Who told you to take their navy?",
"So why did you do it?",
"How many ships?",
"How many men can they carry?",
"Would that be enough to take King's Landing?",
"Please leave me.",
"Not you, Jorah.",
"It appears my liberation of Slaver's Bay isn't going quite as planned.",
"You counciled me against rashness once in Qarth. I didn't listen. It all worked out well.",
"How can I rule Seven Kingdoms if I can't control Slaver's Bay? Why should anyone trust me? Why should anyone follow me?",
"I need to be more than that.",
"I will not let those I have freed slide back into chains. I will not sail for Westeros.",
"I will do what Queens do. I will rule.",
"Zūgagon daor, ñuhys raqiros. Skoros ynot epilū?", 
"I thank him for his prayers.",
"Tell this man I am sorry for his hardship. I cannot bring back his goats. But I will see that he is paid their value, *three* times over.",
"Send the next one in.",
"The noble Hizdahr zo Loraq can speak to me himself.", 
"I thank you.",
"Then it is my honor to receive you.",
"For that he has my gratitude! I should be honored to meet him.",
"Your father crucified innocent children!",
"I am sorry you no longer have a father, but my treatment of the Masters was no crime. You would be wise to remember that.",
"And what traditions do you speak of?",
"And what of the slave children these 'noble' Meereenese have crucified? They were rotting in the sun as well. Would you have begged me for their right to a proper burial?",
"Bury your father, Hizdahr zo Loraq.",
"How many more?",
"Two *hundred* and twelve?",
"Send the next one in.",
"How did you get in here?",
"Don't do that again.",
"These are my private quarters. If I want you here, I will summon you.",
"Tell me why you're here.",
"I've ordered the Second Sons to patrol the streets, to stop the revenge killings.",
"And as for women, there are thousands in Meereen you can pursue.",
"You swore me your sword.",
"So if I command you to stay in Meereen and patrol the streets?",
"Very well. Do what you do best. Take off your clothes.",
"You're here early.",
"You don't approve.",
"You neither approve nor trust.",
"Didn't you fight for the Golden Company before pleding your sword to my brother?",
"I trust you.",
"I could *never* have faith in a man like Daario. That's why I've sent him and the Second Sons to retake Yunkai.",
"I have.",
"That is why I've ordered Daario to execute *every* Master in Yunkai. The Masters tear babies from their mother's arms. They mutilate little boys by the thousands. They train little girls in the art of pleasuring old men. They treat men like beasts, as you said yourself.",
"And repay the slavers with what? Kindness? A fine? Stern warnings?",
"Let the priests argue over good and evil. Slavery is real. I can end it. I will end it. And I *will* end those behind it.",
"And now, you are helping me show them to freedom.",
"The man who came to me the other day about burying his father.",
"He will accompany the Second Sons and serve as my ambassador in Yunkai. He will explain the choice they have before them: they can live in my new world, or they can die in their old one.",
"Go and talk to Daario before he leaves. Tell him I've changed my mind.",
"No. Tell him *you* changed my mind.",
"Why did the Usurper pardon you?",
"No. Speak to me here. Explain it to me.",
"The pardon was signed the year we met. Why were you pardoned? Unless you're saying this document was forged?",
"Why then?",
"What was the content of these letters?",
"What information?",
"You told them I was carrying Drogo's child?",
"Yes or no.",
"Don't call me that. Did you tell them I was carrying Drogo's child?",
"That wine merchant tried to poison me because of your information.",
"Because you knew it was poisoned.",
"You betrayed me. From the first.",
"You sold my secrets to the man who killed my father and stole my brother's throne. You want me to forgive you.",
"Love... Love. How can you say that to me? If you were anyone else, I would have you executed. But you. I don't want you in my city, dead or alive. Go back to your masters in King's Landing, collect your pardon if you can.",
"Don't ever presume to touch me again or speak my name. You have until dusk to collect your things and leave the city. If you are found in Meereen past break of day, I'll have your head thrown into Slaver's Bay.",
"Go. Now.",
"Stay with me.",
"Never betray me.",
"Good.",
"Concessions?",
"I'm not a politician. I'm a Queen.",
"I don't expect the Wise Masters to be happy. Slavery made them rich, I ended slavery.",
"The fighting pits? Where slaves fought slaves to the death?",
"No fighting pits.",
"I do not respect the tradition of human cockfighting.",
"How many times must I say no before you understand?",
"Whatever he wants from me, he's not going to get it. If he really believes I'm going to re-open the fighting pits..",
"What?",
"I'm sorry.",
"You were sold into slavery, forced to fight to the death for the amusement of the Masters, and you're defending the fighting pits?",
"That's why I have the Unsullied patrolling the streets.",
"I don't want another child's bones dropped at my feet. No one's seen Drogon in weeks. For all I know he's flown halfway across the world. I can't control him anymore.",
"Viserion? Rhaegal?",
"Easy! Easy! Easy!",
"It would send a message.",
"Why?",
"Perhaps the only thing that gave him pride was knowing that there was someone lower than he was.",
"Thank you all for your counsel.",
"About what?",
"The Mad King? You're here to remind me of my enemy's lies? Consider me reminded.",
"Go on.",
"I'm not my father.",
"I will not have the Son of the Harpy executed without a fair trial.",
"Why?",
"He was our prisoner, awaiting trial. You had no right." ,
"There are no more slaves. There are no more Masters.", 
"The Harpy's life was not yours to take.", 
"Once, the Masters were the law-", 
"The law is the law.", 
"Take him.", 
"You opened your gates to me because I promised you freedom and justice. One cannot exist without the other.",
"A citizen of Meereen was awaiting trial when this man killed him. The punishment is death.", 
"Leave me.",
"Drogon!",
"Everyone looks happy enough from up here.",
"What?",
"Why?",
"He sang to them?",
"And what did you do?",
"He was good?",
"He told me Rhaegar was good at killing people.",
"And what did you do with the money?",
"*laughs*",
"How many others are there?",
"Will you be joining us, Ser Barristan?",
"I think *I* could protect me from Hizdar zo Loraq. Go, Ser Barristan, sing a song for me.",
"Glory?",
"Is that what you used to tell men before you set them to butchering each other for sport?",
"I do not recognize this tradition.",
"'Barristan the Bold', they called him. He crossed a continent to serve me. He was a loyal friend. And he died in an alley, butchered by cowards who fight behind masks.",
"I prefer your earlier suggestion: round up the leaders of each Great Family and bring them to me.",
"Move forward.", 
"Another step.", 
"They will eat you if I tell them to. They may eat you even if I don't.", 
"Children. Some say I should give up on them. But a good mother never gives up on her children. She disciplines them if she must. But she does not give up on them.",  
"Who is innocent? Maybe all of you are, maybe none of you are. Maybe, I should let the dragons decide.",  
"Don't want to overfeed them.", 
"Tomorrow, perhaps.",
"You will not speak.",
"How do I know you are who you say you are?",
"If you are Tyrion Lannister, why shouldn't I kill you? Pay you back for what your family did to mine.",
"So I should welcome you into my service because you murdered members of your own family?",
"If you'd rather return to the fighting pits, just say the word.",
"And why are you worth meeting? Why should I spend my time listening to you?",
"I will have a very large army. And very large dragons.",
"So you want to advise me. Very well. What would you have me do with him?",
"I swore I would kill him if he ever returned.",
"Why should the people trust a Queen who can't keep her promises?",
"*raises hand*",
"Yes. Many opportunities.",
"No. Not until forced to do so.",
"So I should kill him.",
"Remove Ser Jorah from the city.",
"So have you decided whether I'm worthy of your service?",
"It's probably my safest option.",
"And what would your father have done?",
"Is that why you killed him?",
"I know what my father was, what he did. I know the Mad King earned his name.",
"I'm terrible?",
"Why did you travel to the far side of the world to meet someone terrible?",
"What kind is that?",
"Well, I did re-open the fighting pits. Under my rule, murder will once again become entertainment.",
"Perhaps it won't come to that.",
"Varys? King Robert's Spymaster?",
"Jorah sent my secrets to Varys. For twenty years The Spider oversaw the campaign to find and kill me.",
"But you trust him?",
"The brother who killed my father.",
"Perhaps I will have you killed after all.",
"I'm not going to kill you.",
"No.",
"You're going to advise me. While you can still speak in complete sentences.",
"How to get what I want.",
"If I want jokes, I'll get myself a proper fool.",
"I fought so that no child born in Slaver's Bay will never know what it's like to be fought or sold. I will continue that fight here and beyond. This is not my home.",
"The common people.",
"Lannister, Targaryen, Baratheon, Stark, Tyrell. They're all just spokes in a wheel. This one's on top, then that one's on top, and on and on it spins, crushing those on the ground.",
"I'm not going to stop the wheel. I'm going to break the wheel.",
"Valahd.", 
"We have to go home.",
"Ohh, you poor, sweet thing. Does it hurt? We have to go home.",
"Drogon? Can you take me back to Meereen?",
"How far did you go?",
"Drogon! We need to return! My people need me!",
"Well there's no food. At the very you could hunt us some supper.",
"*grunts*",
"Vo frakho anna vosecchi.",
"Anha Daenerys Vazyol h’Okreseroon Targeryen, Atak ma Hakesoon Mae, Osavvirsak, Khaleesi Mirini, Khaleesi m’Andahli ma Roynari m’Ataki, Khaleesi Havazhofi Hranni, ma Haggey-Assamvak ma Mai Zhavorsi.", 
"Anha vos ochilok ma shafkoa vosecchi. M’anha vo vayyok vo yal che ha shafkea che h’eshnakaan. Avvos vosma shekh yola she jimma ma drivoe she titha.", 
"Anha chiorikemoon ha Khalaan Drogo ki Bharbosi.", 
"Anha nesak. Anha avvirsa khadokh moon.", 
"Hash shafka vidrisofi anna Mirinaan, hash anha vammelisok mekhalasar shafki nem vazha dalen hrazef k’azhi anhoon.", 
"Fin yeri ti?! Eqorasas anna! Anha afichak anhaan nharees yeroa! Anha Mai Zhavorsi! Rizh anni Vezhoon Fin Saja Rhaesheseres! Anha chiorikem Khali Drogo! Zhey ivezho!", 
"Yeri ray esh osoon. Ki jini yeri akhezhi. Anha chiorikem Khali Vezhvena.",
"Hajinaan m’anha Deneris Vazyol, Haggey-Assamvak, Khaleesi Mirini ma Mai Zhavorsi. Vaes anni vos jinne ma shafkoa.", 
"Hazi ale khadosoon.", 
"Ma Khalar Vezhven silokh sh’ajjalan? Anha zigerek athnavaroon.", 
"Anha vos ochoqak Dothrakoa vosecchi.",
"Anha zigere yash chosha.", 
"Yesisi vachrari.", 
"Mori’th samvenosh kash Khal yeri drivo, jin firesof yeri.",
"Me ohazha memé vo drivo k’athaqisinari.",
"Mori ti kijinosi sekosshi. Hash me vallayafa yera tihat mora hezhahhe?", 
"No! Don't hurt her!",
"We will never get out of Vaes Dothrak alive.",
"We can do more than that, and you're going to help me.",
"Ma yer… Qothas k’anni, zhey khaleesi. Vos yer nem holos anhoon.", 
"Hash yeri vo zali nesat rek dirgak anha?",
"Vos, anha vo zalok vos at rek osoon.", 
"Anha nesak rekke anha kovarak. Anha ray dothra jinne hatif ajjin. Hazze, she haz sorfo, anha adakh zhores vezhoon. Ma Dosh Khaleen hake yal anni Vezh Fin Saja Rhaesheseres.", 
"Jinne zhey Drogo ast asqoy vidrie khalasares mae jim, finnaan nakhoe rhaesheser. Dothralat hrazef ido yomme Havazzhifi Kazga ven et vo khal avvos.", 
"Me ast asqoy addrivat mahrazhis fini ondee khogar shiqethi ma ohharat okrenegwin mori. Me ast asqoy anhaan. Hatif Maisi Krazaaji, kash shieraki vitihir asavvasoon.", 
"Ma jinne, ajjin, fin vaese zhokwa jerie Khali Vezhveni? Fin vaesish vemrasoe yeri, finsanney nayat vil ahilee yeri, finsanney hrazef aqaffi yeri k’azhi.", 
"Yeri mahrazhi zhikwi. Torga yeri, Dothraki yanqosoraan zhikwi. Vos at yeroa venoe idrilat mora vosecchi.", 
"Vosma anha venok. Majin anha vidrik.", 
"Yeri vos osili vosecchi. Yeri vadrivoe.", 
"I banished you. Twice. You came back. Twice. And you saved my life. So I can't take you back, and I can't send you away.",
"Is there a cure?",
"How long does it take?",
"I'm sorry. I'm so sorry.",
"Do not walk away from your Queen, Jorah the Andal. You have not been dismissed.",
"You pledged yourself to me. You swore to obey my commands for the rest of your life. Well I command you to find the cure. Wherever it is in this world. I command you to heal yourself, and then return to me.",
"When I take the Seven Kingdoms, I need you by my side.",
"How many day's ride to Meereen?",
"How many ships will I need to bring my Khalasar to Westeros?",
"And who has that many?",
"Nobody yet.",
"I take what is mine.",
"What was I made for?",
"Wait here.",
"Ei khal fin thir nakhaan okke sen dothrakhqoy aloji qisi mae m’avijazeri athdinar mae. Vosma anha vos khal.", 
"Anha vo vokkak sen dothrakhqoy. Anha okkak ei yeri.",
"Anha qafak asqoy yeroa, majin yeri m’athiri m’adrivoe ven qoy qoyi, m’adothrae anni m’avijezeri anna athzhowakaroon.", 
"Anha aqafak san ale yeroa ei Khaloon ray qaf khalasaroon mae!", 
"Hash yeri adothrae hrazef ido yomme Havazzhifi Kazga?", 
"Hash yeri vaddrivi dozge anni ma khogaroon shiqethi mori majin vohhari okrenegwin mori?", 
"Hash yeri vazhi anhaan Rhaeshis Andahli, jin azho me-Khal Drogo ast asqoy mehas hatif Maisi Krazaaji kash shieraki vitihir asavvasoon?", 
"Hash yeri m’anhoon, ma jinne m’ayyeyaan?!", 
"The city's on the rise?",
"Good. Shall we begin?",
"I will crucify the Masters. I will set their fleets afire. Kill every last one of their soldiers and return their cities to the dirt. That is my plan. You don't approve?",
"This is entirely different.",
"We obviously didn't communicate clearly. We are here to discuss your surrender, not mine.",
"My reign has just begun.",
"You brought us a hundred ships from the Iron Fleet, with men to sail them. In return, I expect you'll want me to support your claim to the Iron Islands?",
"What's wrong with you?",
"Has the Iron Islands ever had a Queen before?",
"Lord Tyrion tells me your father was a terrible King.",
"We do, and both murdered by a usurper as well.",
"Will their ships be enough?",
"So why shouldn't I wait for him",
"And I imagine your offer is free to any marriage demands?",
"And you don't want the Seven Kingdoms?",
"And that's all?",
"Reasonable.",
"She's not demanding, she's asking. The others are free to ask as well.",
"Our fathers were evil men, all of us. They left the world worse than they found it. We're not going to do that. We're going to leave the world better than we found it.",
"You will support my claim as Queen of the Seven Kingdoms. And respect the integrity of the Seven Kingdoms. No more reaving, or raving, or raiding, or raping.",
"No more.",
"You're not coming with us.",
"You're not going to Westeros. You're staying here with the Second Sons. There's finally peace in Meereen. You will keep the peace while the people choose their own leaders.",
"You promised me. 'My sword is yours. My life is yours.'. This is what I command.",
"If I'm going to rule in Westeros, I'll need to make alliances. The best way to make alliances is with marriage.",
"I don't know. Maybe no one.",
"I can't bring a lover to Westeros.",
"So that's what you want? To be my mistress?",
"I can't.", 
"No one tells me to do anything.",
"Don't get angry.",
"A great number of women, I imagine.",
"Specific orders will be left for you regarding the welfare of Meereen and the Bay of Dragons.",
"We can't call it 'Slaver's Bay' anymore.",
"Farewell, Daario Naharis.",
"No tears.",
"It's not.",
"Yes, you really are.",
"Do you know what frightens me? I said farewell to a man who loves me. A man I thought I cared for. And I felt nothing, just impatient to get on with it.",
"Well. You have completely failed to console me.",
"It's your counsel, I need.",
"Good. I, umm.. I had something made for you. I'm- I'm not sure if it's right.",
"Tyrion Lannister, I name you Hand of the Queen."
];

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`)
})

client.on('message', message => {
    if (message.isMentioned(client.user)) {
		var rand = messages[Math.floor(Math.random() * messages.length)];
		
		message.channel.send(rand);
	}	
});

client.login(process.env.BOT_TOKEN)